#SRC_MANASTACK_CARDS
#load("./external_files/MANASTACK_CARDS.RData")

SRC_MANASTACK_CARDS <- dbSelectAll("CARDS_DIM", con)

#SRC_MANASTACK_CARDS <- MANASTACK_CARDS[1==1]
#str(SRC_MANASTACK_CARDS)
#str(SRC_MANASTACK_CARDS2)
